### ISSUE TITLE
Attempting!

### ISSUE THREAD

**Issue by binarythinktank** [rishikksh20/FastSpeech2#20]
Hi

Trying to get this to work, with a custom sample set. I'm stuck at the end of this: https://github.com/ivanvovk/DurIAN#6-how-to-align-your-own-data

I don't see how to go from the many .TextGrid files to the 2 filelists that the config needs. 
You mentioned using textgrid in python but I'm not a python dev, do you have a script to convert all of the textgrid files?

Cheers

**Comment by binarythinktank** [comment]
ok, i have figured out how to read the data files:

import textgrid
import sys

f = './alligned/wavs3/{}.TextGrid'.format(sys.argv[1])
tg = textgrid.TextGrid.fromFile(f)

for i in tg.tiers[1].intervals:
        print(i)

which gives me a bunch of these: Interval(0.0, 0.12, sil)

i don't entirely see how this converts to your filelist format though...

looks something like:
[original text]|[the numbers from all of the intervals??]|[the text from all of the intervals]|[filename]

is it both of the numbers? you say convert to frames in the doc, is that x 100?

**Comment by carankt** [comment]
On https://github.com/carankt/FastSpeech2.git
Check the ```Generate_FileList.ipynb```
Hope it Helps!

**Comment by binarythinktank** [comment]
many thanks!

**Comment by binarythinktank** [comment]
@carankt tried running the notebook but getting:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-8cc184c29f14> in <module>
      3 import librosa
      4 import textgrid
----> 5 from utils.files import get_files

ModuleNotFoundError: No module named 'utils.files'

**Comment by carankt** [comment]
@binarythinktank clone the repo and then run. The notebook requires a module from the repo located in `utils/files`

**Comment by binarythinktank** [comment]
@carankt same...

**Comment by carankt** [comment]
Take the latest version of the repo. Added the missing module.

**Comment by binarythinktank** [comment]
thanks, now it works.
this approach is definitely different to my attempt to pull the relevant data out.
Your train.txt file is only 4mb, in my attempt, it somehow ended up being 10Gb....

**Comment by binarythinktank** [comment]
nope, i'm stuck again. If anyone has any idea...


2020-09-14 16:28:53,162 - INFO - ngpu: 1
2020-09-14 16:28:53,162 - INFO - random seed = 1
Using cache found in C:\Users\ml/.cache\torch\hub\seungwonpark_melgan_master
Model is loaded ...
New Training
Batch Size : 16
Trainable Parameters: 26.691M
Loading train data:   0%|                                                                                            | 0/160 [00:06<?, ?it/s]
Traceback (most recent call last):
  File ".\train_fastspeech.py", line 452, in <module>
    main(sys.argv[1:])
  File ".\train_fastspeech.py", line 448, in main
    train(args, hp, hp_str, logger, vocoder)
  File ".\train_fastspeech.py", line 93, in train
    for data in pbar:
  File "C:\Users\ml\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tqdm\std.py", line 1130, in __iter__
    for obj in iterable:
  File "C:\Users\ml\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\dataloader.py", line 354, in __next__
    data = self._next_data()
  File "C:\Users\ml\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\dataloader.py", line 980, in _next_data
    return self._process_data(data)
  File "C:\Users\ml\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\dataloader.py", line 1005, in _process_data
    data.reraise()
  File "C:\Users\ml\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\ml\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\_utils\worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\ml\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\ml\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\home\Downloads\FastSpeech2\dataset\dataloader.py", line 51, in __getitem__
    x = phonemes_to_sequence(x_)
  File "D:\home\Downloads\FastSpeech2\dataset\texts\__init__.py", line 175, in phonemes_to_sequence
    sequence = [_phoneme_to_id[s] for s in string]
  File "D:\home\Downloads\FastSpeech2\dataset\texts\__init__.py", line 175, in <listcomp>
    sequence = [_phoneme_to_id[s] for s in string]
KeyError: 'ER0'

**Comment by carankt** [comment]
The filelist you generated using my repo uses different symbols than this one. You must make adjustments to the filelist or the type of symbols in this repo to move forward.

**Comment by binarythinktank** [comment]
which symbols? not the separator, both are using the pip character?

I will, in parallel, also attempt to use your version.
